"""Declarative base와 제약 naming convention.

naming convention이 없으면 익명 CHECK/UNIQUE가 생기고, 이름이 없는 제약은
Alembic downgrade에서 DROP할 수 없다(04_DB_SPEC.md의 Migration Rule).
convention은 첫 migration 전에 고정해야 한다. 나중에 바꾸면 기존 제약 이름이
전부 달라진다.
"""

from __future__ import annotations

import enum
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)


def bigint_pk() -> Mapped[int]:
    """BIGINT GENERATED BY DEFAULT AS IDENTITY."""
    return mapped_column(sa.BigInteger, sa.Identity(always=False), primary_key=True)


def created_at_column() -> Mapped[datetime]:
    """생성 시각도 **애플리케이션이** 주입된 `now`로 채운다 (ADR-007).

    `server_default now()`를 두지 않는다. 안전망처럼 보이지만 반대로 간다 --- 값을
    빠뜨린 INSERT가 조용히 DB wall clock으로 채워지는 것이 정확히 막으려는 실패다.
    `exploration_recent_days`와 probe cooldown은 주입된 clock을 보는데 `created_at`이
    DB 시계면 두 시계가 갈려 테스트가 거짓 통과한다. default가 없으면 누락이 NOT NULL
    위반으로 즉시 드러난다.
    """
    return mapped_column(sa.DateTime(timezone=True), nullable=False)


def enum_column(python_enum: type[enum.StrEnum], constraint_name: str) -> sa.Enum:
    """VARCHAR + 명명된 CHECK. PostgreSQL native enum은 쓰지 않는다.

    native enum은 Alembic autogenerate가 값 변경을 감지하지 못하고 값 추가가
    트랜잭션 안에서 불가능하다. `event_type`은 17개이고 더 늘어난다.

    `constraint_name`은 naming convention(`ck_%(table_name)s_%(constraint_name)s`)의
    뒷부분이므로 컬럼명만 준다. 여기에 `ck_<table>_`을 붙이면 이름이 두 번 붙는다.
    """
    return sa.Enum(
        python_enum,
        native_enum=False,
        create_constraint=True,
        values_callable=lambda members: [member.value for member in members],
        name=constraint_name,
    )
