"""Declarative base와 제약 naming convention.

naming convention이 없으면 익명 CHECK/UNIQUE가 생기고, 이름이 없는 제약은
Alembic downgrade에서 DROP할 수 없다(04_DB_SPEC.md의 Migration Rule).
convention은 첫 migration 전에 고정해야 한다. 나중에 바꾸면 기존 제약 이름이
전부 달라진다.
"""

from __future__ import annotations

import enum
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)


def bigint_pk() -> Mapped[int]:
    """BIGINT GENERATED BY DEFAULT AS IDENTITY."""
    return mapped_column(sa.BigInteger, sa.Identity(always=False), primary_key=True)


def created_at_column() -> Mapped[datetime]:
    """생성 시각만 DB가 채운다. 그 외 시각 컬럼은 애플리케이션이 채운다."""
    return mapped_column(
        sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
    )


def enum_column(python_enum: type[enum.StrEnum], constraint_name: str) -> sa.Enum:
    """VARCHAR + 명명된 CHECK. PostgreSQL native enum은 쓰지 않는다.

    native enum은 Alembic autogenerate가 값 변경을 감지하지 못하고 값 추가가
    트랜잭션 안에서 불가능하다. `event_type`은 17개이고 더 늘어난다.

    `constraint_name`은 naming convention(`ck_%(table_name)s_%(constraint_name)s`)의
    뒷부분이므로 컬럼명만 준다. 여기에 `ck_<table>_`을 붙이면 이름이 두 번 붙는다.
    """
    return sa.Enum(
        python_enum,
        native_enum=False,
        create_constraint=True,
        values_callable=lambda members: [member.value for member in members],
        name=constraint_name,
    )
