"""initial schema

04_DB_SPEC.md의 19개 테이블. 빈 DB에 대해 autogenerate한 뒤 손으로 검토했다.

Revision ID: 0001
Revises:
Create Date: 2026-09-11 20:19:59.894355

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "GENERATE_SENTENCE_BATCH",
                "EXPLAIN_ITEM",
                "GENERATE_REVIEW_CONTEXT",
                name="job_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "validated",
                "completed",
                "retry",
                "failed",
                "dead_letter",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("result_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_generation_jobs_idempotency_key")),
    )
    op.create_index(
        "ix_generation_jobs_status_next_attempt_at",
        "generation_jobs",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "learning_items",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "word",
                "grammar",
                "expression",
                name="type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("lemma", sa.Text(), nullable=False),
        sa.Column("reading", sa.Text(), nullable=False),
        sa.Column("default_meaning", sa.Text(), nullable=False),
        sa.Column("difficulty_label", sa.Text(), nullable=True),
        sa.Column("topic_tags", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "origin",
            sa.Enum("seed", "generated", name="origin", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_items")),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "GENERATE_SENTENCE_BATCH",
                "EXPLAIN_ITEM",
                "GENERATE_REVIEW_CONTEXT",
                name="task_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint(
            "task_type", "version", name=op.f("uq_prompt_versions_task_type_version")
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("login_id", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column(
            "starting_level",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                name="starting_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint(
            "login_id ~ '^[a-z0-9._+@-]{3,64}$'", name=op.f("ck_users_login_id_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("login_id", name=op.f("uq_users_login_id")),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_sessions_token_hash")),
    )
    op.create_index("ix_auth_sessions_user_id", "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "review_states",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("learning_item_id", sa.BigInteger(), nullable=False),
        sa.Column("stability", sa.Double(), nullable=True),
        sa.Column("difficulty", sa.Double(), nullable=True),
        sa.Column("state", sa.SmallInteger(), nullable=False),
        sa.Column("step", sa.Integer(), nullable=True),
        sa.Column("last_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reps", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("lapses", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("fsrs_params_version", sa.Text(), nullable=False),
        sa.Column("deferred_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "meaningful_exposure_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.CheckConstraint("state IN (1, 2, 3)", name=op.f("ck_review_states_state_enum")),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_review_states_learning_item_id_learning_items"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_review_states_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_states")),
        sa.UniqueConstraint(
            "user_id", "learning_item_id", name=op.f("uq_review_states_user_id_learning_item_id")
        ),
    )
    op.create_index(
        "ix_review_states_user_id_next_review_at",
        "review_states",
        ["user_id", "next_review_at"],
        unique=False,
    )
    op.create_table(
        "sentences",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("japanese", sa.Text(), nullable=False),
        sa.Column("korean_translation", sa.Text(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "generated", "seed", name="source_type", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column(
            "difficulty_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "provenance_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("generation_job_id", sa.BigInteger(), nullable=True),
        sa.Column("parent_sentence_id", sa.BigInteger(), nullable=True),
        sa.Column("normalized_hash", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "validated",
                "quarantined",
                "retired",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_job_id"],
            ["generation_jobs.id"],
            name=op.f("fk_sentences_generation_job_id_generation_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_sentence_id"],
            ["sentences.id"],
            name=op.f("fk_sentences_parent_sentence_id_sentences"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sentences")),
    )
    op.create_index("ix_sentences_normalized_hash", "sentences", ["normalized_hash"], unique=False)
    op.create_table(
        "study_sessions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_seconds", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("target_minutes", sa.Integer(), nullable=False),
        sa.Column("extended_minutes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "policy_snapshot_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "summary_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_study_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_sessions")),
    )
    op.create_index(
        "ix_study_sessions_user_id_started_at",
        "study_sessions",
        ["user_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "user_mastery",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("learning_item_id", sa.BigInteger(), nullable=False),
        sa.Column("comprehension_mastery", sa.Double(), nullable=True),
        sa.Column("listening_mastery", sa.Double(), nullable=True),
        sa.Column("evidence_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("mastery_algorithm_version", sa.Text(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "comprehension_mastery IS NULL OR (comprehension_mastery >= 0.0 AND comprehension_mastery <= 1.0)",
            name=op.f("ck_user_mastery_comprehension_mastery_range"),
        ),
        sa.CheckConstraint(
            "listening_mastery IS NULL OR (listening_mastery >= 0.0 AND listening_mastery <= 1.0)",
            name=op.f("ck_user_mastery_listening_mastery_range"),
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_user_mastery_learning_item_id_learning_items"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_mastery_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_mastery")),
        sa.UniqueConstraint(
            "user_id", "learning_item_id", name=op.f("uq_user_mastery_user_id_learning_item_id")
        ),
    )
    op.create_table(
        "sentence_items",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("sentence_id", sa.BigInteger(), nullable=False),
        sa.Column("learning_item_id", sa.BigInteger(), nullable=False),
        sa.Column("surface_form", sa.Text(), nullable=False),
        sa.Column("is_tappable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_sentence_items_learning_item_id_learning_items"),
        ),
        sa.ForeignKeyConstraint(
            ["sentence_id"], ["sentences.id"], name=op.f("fk_sentence_items_sentence_id_sentences")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sentence_items")),
    )
    op.create_index(
        "ix_sentence_items_learning_item_id", "sentence_items", ["learning_item_id"], unique=False
    )
    op.create_index(
        "ix_sentence_items_sentence_id", "sentence_items", ["sentence_id"], unique=False
    )
    op.create_table(
        "user_item_learning_state",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("learning_item_id", sa.BigInteger(), nullable=False),
        sa.Column("anchor_sentence_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "context_stage",
            sa.Enum(
                "anchor",
                "near_original",
                "varied",
                "new_context",
                name="context_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "passive_no_signal_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_probe_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("probe_skip_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "is_active_learning_target",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["anchor_sentence_id"],
            ["sentences.id"],
            name=op.f("fk_user_item_learning_state_anchor_sentence_id_sentences"),
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_user_item_learning_state_learning_item_id_learning_items"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_item_learning_state_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_item_learning_state")),
        sa.UniqueConstraint(
            "user_id",
            "learning_item_id",
            name=op.f("uq_user_item_learning_state_user_id_learning_item_id"),
        ),
    )
    op.create_table(
        "user_sentence_candidates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("sentence_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "presentation_role",
            sa.Enum(
                "review",
                "new",
                "exploration",
                name="presentation_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "review_reason",
            sa.Enum(
                "fsrs_due",
                "reinforcement",
                "context_repair",
                name="review_reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "context_stage",
            sa.Enum(
                "anchor",
                "near_original",
                "varied",
                "new_context",
                name="context_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "ready",
                "shown",
                "consumed",
                "quarantined",
                "expired",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sentence_id"],
            ["sentences.id"],
            name=op.f("fk_user_sentence_candidates_sentence_id_sentences"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_sentence_candidates_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sentence_candidates")),
    )
    op.create_index(
        "ix_user_sentence_candidates_user_id_status_role",
        "user_sentence_candidates",
        ["user_id", "status", "presentation_role"],
        unique=False,
    )
    # partial unique: materialization idempotency (04_DB_SPEC.md, ADR-010).
    # shown / consumed / quarantined / expired를 제외해야 같은 문장을 나중에 다시
    # candidate로 만들 수 있다 (contextual review의 전제).
    op.create_index(
        "uq_user_sentence_candidates_active",
        "user_sentence_candidates",
        ["user_id", "sentence_id", "presentation_role", "context_stage"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'ready')"),
    )
    op.create_table(
        "sentence_item_explanations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("sentence_item_id", sa.BigInteger(), nullable=False),
        sa.Column("reading", sa.Text(), nullable=False),
        sa.Column("core_meaning", sa.Text(), nullable=False),
        sa.Column("meaning_in_context", sa.Text(), nullable=False),
        sa.Column("nuance", sa.Text(), nullable=False),
        sa.Column("example_sentence", sa.Text(), nullable=False),
        sa.Column("example_translation", sa.Text(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "validated",
                "quarantined",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sentence_item_id"],
            ["sentence_items.id"],
            name=op.f("fk_sentence_item_explanations_sentence_item_id_sentence_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sentence_item_explanations")),
    )
    op.create_index(
        "ix_sentence_item_explanations_sentence_item_id",
        "sentence_item_explanations",
        ["sentence_item_id"],
        unique=False,
    )
    op.create_table(
        "sentence_item_spans",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("sentence_item_id", sa.BigInteger(), nullable=False),
        sa.Column("start_codepoint", sa.Integer(), nullable=False),
        sa.Column("end_codepoint", sa.Integer(), nullable=False),
        sa.Column("span_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "start_codepoint >= 0 AND end_codepoint > start_codepoint",
            name=op.f("ck_sentence_item_spans_codepoint_range"),
        ),
        sa.ForeignKeyConstraint(
            ["sentence_item_id"],
            ["sentence_items.id"],
            name=op.f("fk_sentence_item_spans_sentence_item_id_sentence_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sentence_item_spans")),
        sa.UniqueConstraint(
            "sentence_item_id",
            "span_order",
            name=op.f("uq_sentence_item_spans_sentence_item_id_span_order"),
        ),
    )
    op.create_table(
        "study_presentations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("study_session_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("candidate_id", sa.BigInteger(), nullable=False),
        sa.Column("sentence_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "presentation_role",
            sa.Enum(
                "review",
                "new",
                "exploration",
                name="presentation_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "review_reason",
            sa.Enum(
                "fsrs_due",
                "reinforcement",
                "context_repair",
                name="review_reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "context_stage",
            sa.Enum(
                "anchor",
                "near_original",
                "varied",
                "new_context",
                name="context_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("shown_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["user_sentence_candidates.id"],
            name=op.f("fk_study_presentations_candidate_id_user_sentence_candidates"),
        ),
        sa.ForeignKeyConstraint(
            ["sentence_id"],
            ["sentences.id"],
            name=op.f("fk_study_presentations_sentence_id_sentences"),
        ),
        sa.ForeignKeyConstraint(
            ["study_session_id"],
            ["study_sessions.id"],
            name=op.f("fk_study_presentations_study_session_id_study_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_study_presentations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_presentations")),
    )
    op.create_index(
        "ix_study_presentations_study_session_id",
        "study_presentations",
        ["study_session_id"],
        unique=False,
    )
    op.create_index(
        "ix_study_presentations_user_id_shown_at",
        "study_presentations",
        ["user_id", "shown_at"],
        unique=False,
    )
    op.create_table(
        "user_sentence_candidate_targets",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("candidate_id", sa.BigInteger(), nullable=False),
        sa.Column("learning_item_id", sa.BigInteger(), nullable=False),
        sa.Column("is_new_item", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["user_sentence_candidates.id"],
            name=op.f("fk_user_sentence_candidate_targets_candidate_id_user_sentence_candidates"),
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_user_sentence_candidate_targets_learning_item_id_learning_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sentence_candidate_targets")),
        sa.UniqueConstraint(
            "candidate_id",
            "learning_item_id",
            name=op.f("uq_user_sentence_candidate_targets_candidate_id_learning_item_id"),
        ),
    )
    op.create_table(
        "content_flags",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("sentence_id", sa.BigInteger(), nullable=True),
        sa.Column("learning_item_id", sa.BigInteger(), nullable=True),
        sa.Column("study_presentation_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "unnatural",
                "wrong",
                "too_easy",
                "too_hard",
                "other",
                name="reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_content_flags_learning_item_id_learning_items"),
        ),
        sa.ForeignKeyConstraint(
            ["sentence_id"], ["sentences.id"], name=op.f("fk_content_flags_sentence_id_sentences")
        ),
        sa.ForeignKeyConstraint(
            ["study_presentation_id"],
            ["study_presentations.id"],
            name=op.f("fk_content_flags_study_presentation_id_study_presentations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_content_flags_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_flags")),
    )
    op.create_index("ix_content_flags_user_id", "content_flags", ["user_id"], unique=False)
    op.create_table(
        "item_exposures",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("learning_item_id", sa.BigInteger(), nullable=False),
        sa.Column("study_presentation_id", sa.BigInteger(), nullable=False),
        sa.Column("sentence_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "modality",
            sa.Enum("reading", name="modality", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "context_stage",
            sa.Enum(
                "anchor",
                "near_original",
                "varied",
                "new_context",
                name="context_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_item_exposures_learning_item_id_learning_items"),
        ),
        sa.ForeignKeyConstraint(
            ["sentence_id"], ["sentences.id"], name=op.f("fk_item_exposures_sentence_id_sentences")
        ),
        sa.ForeignKeyConstraint(
            ["study_presentation_id"],
            ["study_presentations.id"],
            name=op.f("fk_item_exposures_study_presentation_id_study_presentations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_item_exposures_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_exposures")),
        sa.UniqueConstraint(
            "study_presentation_id",
            "learning_item_id",
            name=op.f("uq_item_exposures_study_presentation_id_learning_item_id"),
        ),
    )
    op.create_index(
        "ix_item_exposures_user_id_learning_item_id_created_at",
        "item_exposures",
        ["user_id", "learning_item_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "learning_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("study_session_id", sa.BigInteger(), nullable=False),
        sa.Column("study_presentation_id", sa.BigInteger(), nullable=True),
        sa.Column("sentence_id", sa.BigInteger(), nullable=True),
        sa.Column("learning_item_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "session_started",
                "sentence_viewed",
                "sentence_completed",
                "item_clicked",
                "explanation_revealed",
                "translation_revealed",
                "self_report_known",
                "self_report_uncertain",
                "self_report_unknown",
                "mastery_probe_shown",
                "mastery_probe_known",
                "mastery_probe_uncertain",
                "mastery_probe_unknown",
                "mastery_probe_skipped",
                "content_flagged",
                "session_extended",
                "session_finished",
                name="event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("client_event_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_learning_events_learning_item_id_learning_items"),
        ),
        sa.ForeignKeyConstraint(
            ["sentence_id"], ["sentences.id"], name=op.f("fk_learning_events_sentence_id_sentences")
        ),
        sa.ForeignKeyConstraint(
            ["study_presentation_id"],
            ["study_presentations.id"],
            name=op.f("fk_learning_events_study_presentation_id_study_presentations"),
        ),
        sa.ForeignKeyConstraint(
            ["study_session_id"],
            ["study_sessions.id"],
            name=op.f("fk_learning_events_study_session_id_study_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learning_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_events")),
        sa.UniqueConstraint(
            "user_id", "client_event_id", name=op.f("uq_learning_events_user_id_client_event_id")
        ),
    )
    op.create_index(
        "ix_learning_events_user_id_created_at",
        "learning_events",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_learning_events_user_id_created_at", table_name="learning_events")
    op.drop_table("learning_events")
    op.drop_index(
        "ix_item_exposures_user_id_learning_item_id_created_at", table_name="item_exposures"
    )
    op.drop_table("item_exposures")
    op.drop_index("ix_content_flags_user_id", table_name="content_flags")
    op.drop_table("content_flags")
    op.drop_table("user_sentence_candidate_targets")
    op.drop_index("ix_study_presentations_user_id_shown_at", table_name="study_presentations")
    op.drop_index("ix_study_presentations_study_session_id", table_name="study_presentations")
    op.drop_table("study_presentations")
    op.drop_table("sentence_item_spans")
    op.drop_index(
        "ix_sentence_item_explanations_sentence_item_id", table_name="sentence_item_explanations"
    )
    op.drop_table("sentence_item_explanations")
    op.drop_index("uq_user_sentence_candidates_active", table_name="user_sentence_candidates")
    op.drop_index(
        "ix_user_sentence_candidates_user_id_status_role", table_name="user_sentence_candidates"
    )
    op.drop_table("user_sentence_candidates")
    op.drop_table("user_item_learning_state")
    op.drop_index("ix_sentence_items_sentence_id", table_name="sentence_items")
    op.drop_index("ix_sentence_items_learning_item_id", table_name="sentence_items")
    op.drop_table("sentence_items")
    op.drop_table("user_mastery")
    op.drop_index("ix_study_sessions_user_id_started_at", table_name="study_sessions")
    op.drop_table("study_sessions")
    op.drop_index("ix_sentences_normalized_hash", table_name="sentences")
    op.drop_table("sentences")
    op.drop_index("ix_review_states_user_id_next_review_at", table_name="review_states")
    op.drop_table("review_states")
    op.drop_index("ix_auth_sessions_user_id", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("users")
    op.drop_table("prompt_versions")
    op.drop_table("learning_items")
    op.drop_index("ix_generation_jobs_status_next_attempt_at", table_name="generation_jobs")
    op.drop_table("generation_jobs")
    # ### end Alembic commands ###
